services:
  db:
    image: my-postgres-with-data:latest
    restart: always
    environment:
      POSTGRES_USER: recipeuser
      POSTGRES_PASSWORD: recipepass
      POSTGRES_DB: recipedb
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: recipeuser
      DB_PASSWORD: recipepass
      DB_NAME: recipedb
    depends_on:
      - db
    volumes:
      - ./public:/app/public
    command:
      [
        "sh",
        "-c",
        "npm install && sleep 5 && node scripts/importRecipes.js && npm start",
      ]
